// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQOrB7dYn42RhUsBDj6L9DObzewwk2b8Y',
    appId: '1:518109219610:web:e70bf981cf1b6eb9ce3aa3',
    messagingSenderId: '518109219610',
    projectId: 'videostreaming-df822',
    authDomain: 'videostreaming-df822.firebaseapp.com',
    storageBucket: 'videostreaming-df822.appspot.com',
    measurementId: 'G-J73BT8CMB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvDgZ15OeWkcmK_WNBSnLFm0-Pzk_c9tw',
    appId: '1:518109219610:android:205855e02e1f81ddce3aa3',
    messagingSenderId: '518109219610',
    projectId: 'videostreaming-df822',
    storageBucket: 'videostreaming-df822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkwXgKC-cfOnVTHI7rVieei9k4UEDedZk',
    appId: '1:518109219610:ios:ae8202a128bbcbeece3aa3',
    messagingSenderId: '518109219610',
    projectId: 'videostreaming-df822',
    storageBucket: 'videostreaming-df822.appspot.com',
    iosBundleId: 'com.vs.videoStreaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkwXgKC-cfOnVTHI7rVieei9k4UEDedZk',
    appId: '1:518109219610:ios:ae8202a128bbcbeece3aa3',
    messagingSenderId: '518109219610',
    projectId: 'videostreaming-df822',
    storageBucket: 'videostreaming-df822.appspot.com',
    iosBundleId: 'com.vs.videoStreaming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQOrB7dYn42RhUsBDj6L9DObzewwk2b8Y',
    appId: '1:518109219610:web:0ff413056d7d0730ce3aa3',
    messagingSenderId: '518109219610',
    projectId: 'videostreaming-df822',
    authDomain: 'videostreaming-df822.firebaseapp.com',
    storageBucket: 'videostreaming-df822.appspot.com',
    measurementId: 'G-ZSFMNPZRVZ',
  );
}
